### PR TITLE
Add online documentation setup

### PR DESCRIPTION
**Pull request by rth**
This PR adds a setup to build online documentation (issue https://github.com/bsmurphy/PyKrige/issues/14), which can be done for instance with,

```bash
conda create -n pykrige-env numpy scipy matplotlib python=3.6
cd PyKrige
python setup.py develop
# these are only used to build the docs
pip install sphinx recommonmark sphinxcontrib-napoleon sphinx_rtd_theme sphinx-gallery pillow
cd doc/
make html
```
which would produce the html docs under `_build/html`. Temporary the current version of the generated docs could be visualized [here](http://r0h.eu/d/PyKrige-docs/index.html) but we would need to host those e.g. on  https://readthedocs.io

This PR,

 - setup to automatically generate the class/function documentation form the code
 - setup to run examples and visualize the output with with sphinx-gallery
 - changes the README from .md to .rst so that it can be included in the docs (writing documentation with .md files is also supported, I just have not figured out yet how to include .md file from another .md file..)

it does not contain,
   
 - setup to update the docs automatically online (will be added in the next PR)
 - docstrings formatting would need to be improved for the autodoc to parse them correctly (cf. e.g. [Numpy style docstring formating](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_numpy.html))

@bsmurphy  Could you please activate CircleCI on this repo (which could be used to build the docs) ? Thanks!

### CODE REVIEW

**Comment by basaks** [comment]
I got this:

`ValueError: Sphinx-Gallery relies on the matplotlib 'agg' backend to render figures and write them to files. You are currently using the TkAgg backend. Sphinx-Gallery will terminate the build now, because changing backends is not well supported by matplotlib. We advise you to move sphinx_gallery imports before any matplotlib-dependent import. Moving sphinx_gallery imports at the top of your conf.py file should fix this issue`


Fixed it by adding the following lines on top of `conf.py`:
```
import matplotlib
matplotlib.use("Agg")
```

The error is probably dependent on sphinx version, but adding those tow lines on top of conf.py won't hurt.

**Comment by rth** [comment]
Thanks for testing it @basaks !  I added `matplotlib.use("Agg")` to `conf.py`.

**Comment by basaks** [comment]
For including markdowns:
```
from recommonmark.parser import CommonMarkParser
source_parsers = {'.md': CommonMarkParser}
source_suffix = ['.rst', '.md']
```

**Comment by rth** [comment]
@basaks Yep, the `doc/conf.py` contains those lines already..

**Comment by rth** [comment]
@bsmurphy , @basaks  could you please merge this if you are OK with it? Thanks.

**Comment by bsmurphy** [comment]
Yep, this looks great. I'll work on the CircleCI setup.

**Comment by basaks** [comment]
thanks for this @rth.

**Pull request merged**
