### PR TITLE
Benchmark scripts

### PR DESCRIPTION
**Pull request by rth**
This PR adds a quick benchmark script (for now for ordinary kriging) that could help with the optimization (for instance in issue #35 ).

The code is not so clean but it's mostly string formatting and this is not part of the core libary. An example of the output can be found below,
```
(krige-env) rth@byzance benchmarks % python kriging_benchmarks.py                  
================================================================================
           N_dim=2, N_train=400, N_test=1000
================================================================================

 # Training the model 

t_train (s) |      power |   gaussian |  spherical |exponential |     linear 
------------------------------------------------------------------------------
   Training |      0.031 |      0.022 |      0.027 |      0.028 |      0.024 

 # Predicting kriging points 

 t_test (s) | vectorized |       loop |          C 
----------------------------------------------------
  N_nn=None |      0.049 |       0.09 |      0.045 
    N_nn=10 |            |       0.12 |     0.0098 
    N_nn=50 |            |       0.24 |      0.042 
   N_nn=100 |            |       0.35 |       0.11 
================================================================================
           N_dim=2, N_train=400, N_test=2000
================================================================================

 # Training the model 

t_train (s) |      power |   gaussian |  spherical |exponential |     linear 
------------------------------------------------------------------------------
   Training |       0.02 |      0.021 |      0.021 |       0.02 |       0.02 

 # Predicting kriging points 

 t_test (s) | vectorized |       loop |          C 
----------------------------------------------------
  N_nn=None |      0.078 |       0.15 |      0.075 
    N_nn=10 |            |       0.23 |      0.015 
    N_nn=50 |            |       0.36 |      0.081 
   N_nn=100 |            |       0.64 |       0.22 
================================================================================
           N_dim=2, N_train=800, N_test=2000
================================================================================

 # Training the model 

t_train (s) |      power |   gaussian |  spherical |exponential |     linear 
------------------------------------------------------------------------------
   Training |      0.077 |      0.079 |      0.079 |      0.078 |      0.078 

 # Predicting kriging points 

 t_test (s) | vectorized |       loop |          C 
----------------------------------------------------
  N_nn=None |       0.22 |       0.64 |       0.54 
    N_nn=10 |            |       0.24 |      0.025 
    N_nn=50 |            |       0.39 |      0.097 
   N_nn=100 |            |       0.75 |       0.27
```

**Update**: the `N_nn` variable refers to the number of points in the moving window.

### CODE REVIEW

**Comment by basaks** [comment]
@rth  Tomorrow?
Sorry I missed this one earlier.

**Comment by rth** [comment]
@basaks Sure, no problem, thank you!

**Comment by basaks** [comment]
Hi @rth See branch `benchmark`.
I have fixed some pep8. Let's merge it.

**Comment by rth** [comment]
Thanks for the review @basaks !
I added your commit from the `benchmark` branch, and I agree with most changes except,
   - it might be better to keep the space between variable, `:` and type in the [numpy style docstrings](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_numpy.html) as otherwise it doesn't get parsed correctly by sphinx
   - I do quite like the notations with capital X and small y, inspired by scikit-learn,
     untitled

but anyway it's just style nitpicking on my part as we don't have docs yet, and this is not going to be part of the core library anyway...
Feel free to "Squash and merge" this PR (and delete the `master/benchmarks` branch) if you are OK with this. Thanks!

**Comment by basaks** [comment]
yes, you are probably right. We should add these issues using a .pylintrc at an appropriate time.

**Pull request merged**
